name: webtoon
description: "A Webtoon Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  cupertino_icons: 1.0.8
  easy_localization: 3.0.7+1
  flutter:
    sdk: flutter
  dio: ^5.8.0+1
  cached_network_image: ^3.4.1
  shared_preferences: 2.5.3
  url_launcher: 6.3.2
  async: 2.13.0
  json_annotation: 4.9.0
  freezed_annotation: 3.1.0

dev_dependencies:
  build_runner: 2.6.0
  flutter_gen: 5.11.0
  flutter_lints: 6.0.0
  flutter_test:
    sdk: flutter
  source_gen: 3.0.0
  freezed: ^3.2.0
  json_serializable: ^6.10.0

flutter:
  uses-material-design: true

  assets:
    - assets/translations/

flutter_gen:
  output: lib/common/presentation/.generated
  line_length: 120
  assets:
    outputs:
      package_parameter_enabled: true